site_name: Nuvola
site_url: https://sitename.example

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: amber
      # primary: blue
      # accent: indigo
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: amber
      # primary: blue
      # accent: indigo
      accent: deep orange
      background: white
      text: black

  font:
    text: Merriweather Sans
    # text: 'Roboto, sans-serif'
    code: Red Hat Mono
    # code: 'Roboto Mono, monospace'
  logo: fontawesome/solid/w
  # logo: 'images/logo.png'
  # favicon: 'images/favicon.ico'
  search: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - typeset
  - privacy
